import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import HotelOffer from "../componnets/HotelOffer";
import NavBar from "../componnets/NavBar";
import { resorts } from "../config/resorts";
import styles from "../styles/Home.module.css";

export type hotelOffer = {
  name: string;
  image: string;
  price: string;
}

const Home: NextPage = () => {
  const [site, setSite] = useState('');
  const [guests, setGuests] = useState(0);
  const [from, setFrom] = useState("");
  const [to, setTo] = useState("");
  const [data, setData] = useState([] as hotelOffer[])

  const HotelOffers = data.map((offer, i) => <HotelOffer name={offer.name} key={i} image={offer.image} price={offer.price}/>)

  useEffect(() => {
    const source = new EventSource(`http://localhost:7701/api/vacation?ski_site=${findSiteNum(site)}&from_date=${from}&to_date=${to}&group_size=${guests}`);

    source.addEventListener('open', () => {
      console.log('SSE opened!');
    });

    source.addEventListener('message', (e) => {
      console.log(e.data);
      const message = JSON.parse(e.data);
      const newHotels = message.map((hotel: any) => {
        return {
          name: hotel.HotelName,
          image: hotel.HotelDescriptiveContent.Images.filter((img: { MainImage?: string; }) => img.MainImage == 'True')[0].URL,
          price: hotel.PricesInfo.AmountAfterTax.split('.')[0],
        }
      });

      const newData = [...data, ...newHotels];
      setData(newData);
      // setDonation(data);
    });

    source.addEventListener('error', (e) => {
      console.error('Error: ',  e);
      setData([]);
    });

    return () => {
      source.close();
    };
  }, [site, guests, from, to, data]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav>
        <ul className={styles.ul}>
          <li>
            <input
              placeholder="site name"
              value={site}
              onChange={(e) => setSite((e.target.value))}
              type="text"
              name="site"
              id="site"
            />
          </li>
          <li>
            <input
              type="number"
              value={guests}
              onChange={(e) => setGuests(parseInt(e.target.value))}
              placeholder="people"
              name="guests"
              id="guests"
            />
          </li>
          <li>
            <input
              type="date"
              value={from}
              onChange={(e) => setFrom(e.target.value)}
              placeholder="from"
              name="from"
              id="from"
            />
          </li>
          <li>
            <input
              type="date"
              value={to}
              onChange={(e) => setTo(e.target.value)}
              placeholder="to"
              name="to"
              id="to"
            />
          </li>
        </ul>
      </nav>

      <div className={styles.offer_wrapper}>
        {HotelOffers}
      </div>
    </div>
  );
};

function findSiteNum(siteName: string) {
  return resorts.find(resort => resort.name == siteName)?.id
}

export default Home;
